# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LastBite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImageSwiftUI'
  # Firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  #King fisher for caching images
  pod 'Kingfisher'

  # Pods for LastBite

  target 'LastBiteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LastBiteUITests' do
    # Pods for testing
  end

end
